# Learn numpy basics including array creation and slicing

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
np.zeros(2)

array([0., 0.])

In [5]:
np.ones(2)

array([1., 1.])

In [6]:
np.arange(4)

array([0, 1, 2, 3])

In [7]:
np.arange(0, 9, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
np.ones(2, dtype=np.int64)

array([1, 1])

In [10]:
a = np.array([[1, 2], [3, 4]])

In [11]:
b = np.array([5, 6])

In [12]:
display(a)
display(b[np.newaxis, :])

array([[1, 2],
       [3, 4]])

array([[5, 6]])

In [13]:
np.concatenate((a, b[np.newaxis, :]))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
arr = np.arange(3)

In [15]:
arr.shape

(3,)

In [16]:
row_vector = arr[np.newaxis, :]

In [17]:
row_vector.shape

(1, 3)

In [18]:
col_vector = arr[:, np.newaxis]

In [19]:
col_vector.shape

(3, 1)