# Numpy slice array for k-fold cross validation

In [1]:
import numpy as np

In [2]:
arr = [1, 2, 3, 4, 5]

In [11]:
arr_without_3rd_elem = arr[:3] + arr[3:]

In [12]:
arr_without_3rd_elem

[1, 2, 3, 4, 5]

In [13]:
arr[:3]

[1, 2, 3]

In [21]:
def array_without_kth_elem(arr, k):
    return arr[:k] + arr[k+1:]

In [22]:
for idx, val in enumerate(arr):
    print(array_without_kth_elem(arr, idx))

[2, 3, 4, 5]
[1, 3, 4, 5]
[1, 2, 4, 5]
[1, 2, 3, 5]
[1, 2, 3, 4]


In [30]:
my_2d_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
display(my_2d_arr)
display(my_2d_arr.shape)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

(4, 3)

In [39]:
train_data = np.delete(my_2d_arr, 1, axis=0)
train_data

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
validation_data = my_2d_arr[1]
validation_data

array([4, 5, 6])

In [47]:
mask = np.ones(len(my_2d_arr), dtype=bool)
mask

array([ True,  True,  True,  True])

In [48]:
mask[1] =  False
train_data = my_2d_arr[mask]
train_data

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
validation_data = my_2d_arr[~mask]
validation_data.flatten()  # convert 2d array to 1d array

array([4, 5, 6])