# Create a monomial basis function for training non-linear regression

In [1]:
import numpy as np

In [2]:
x_1d = np.array([2.0, 3.0])

In [3]:
def sum_to_target(length, target):
    if length == 1:
        yield (target,)
    else:
        for val in range(target + 1):
            for perm in sum_to_target(length - 1, target - val):
                yield (val,) + perm

In [4]:
def sum_upto_target(length, target):
    ways = []
    for i in range(target + 1):
        ways.extend(list(sum_to_target(length, i)))
    return ways

In [5]:
power_array = np.array(sum_upto_target(length=2, target=3))

In [6]:
power_array

array([[0, 0],
       [0, 1],
       [1, 0],
       [0, 2],
       [1, 1],
       [2, 0],
       [0, 3],
       [1, 2],
       [2, 1],
       [3, 0]])

In [7]:
def monomial_basis_v1(x, d):
    m = x.shape[0]
    power_array = np.array(sum_upto_target(length=m, target=d))
    features = np.product(np.power(x, power_array), axis=1)
    return features

In [8]:
monomial_basis_v1(x_1d, d=2)

array([1., 3., 2., 9., 6., 4.])

In [26]:
x_2d = np.array([[2.0, 3.0], [2.5, 3.5], [0.5, 1.5]])

In [27]:
x_2d.shape

(3, 2)

In [28]:
def calculate_basis_1d(x, power_array):
    return np.product(np.power(x, power_array), axis=1)

In [29]:
def monomial_basis_v2(x, d):
    m = x.shape[1]
    power_array = np.array(sum_upto_target(length=m, target=d))
    features = np.apply_along_axis(calculate_basis_1d, 1, x, power_array)
    return features

In [30]:
monomial_basis_v2(x_2d, d=2)

array([[ 1.  ,  3.  ,  2.  ,  9.  ,  6.  ,  4.  ],
       [ 1.  ,  3.5 ,  2.5 , 12.25,  8.75,  6.25],
       [ 1.  ,  1.5 ,  0.5 ,  2.25,  0.75,  0.25]])

In [31]:
%timeit monomial_basis_v2(x_2d, d=21)

502 µs ± 8.09 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [55]:
x_2d_large = np.tile(x_2d, (100, 1))

In [56]:
%timeit monomial_basis_v2(x_2d_large, d=21)

17.9 ms ± 278 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [57]:
def monomial_basis_v3(x, d):
    m = x.shape[1]
    power_array = np.array(sum_upto_target(length=m, target=d))
    y = np.expand_dims(x, axis=2)
    features = np.prod(np.power(y, power_array.T), axis=1)
    return features
    

In [58]:
%timeit monomial_basis_v3(x_2d, d=21)

397 µs ± 12.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [59]:
%timeit monomial_basis_v3(x_2d_large, d=21)

10.5 ms ± 85.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [72]:
%timeit sum_upto_target(2, 21)

133 µs ± 1.04 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
